### ISSUE TITLE
Getting unknown property: DefaultController::provider

### ISSUE THREAD

**Issue by c7v** [amocrm/amocrm-oauth-client#13]
Использую Yii2, скопировал код (как всегда не глядя) запустил приложение и выдаёт ошибку: Getting unknown property: DefaultController::provider скопированный код из примера [README.md](https://github.com/amocrm/amocrm-oauth-client/blob/master/README.md) "Обработка кода авторизации (Authorization Code)". В примере используется строка:

```php
$token = $this->provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
]);
```
Вопрос, откуда $this? Что должно быть в $this->provider? Где назначение $this->provider в примере? В примере [example.php](https://github.com/amocrm/amocrm-oauth-client/blob/master/example.php) я не нашёл что-то связанное с $this->provider

Автор, благодарю за код и вложенные старания.

**Comment by bessudnov** [comment]
Исправили ошибку в README

**Comment by c7v** [comment]
Спасибо! 👍🏼
