### ISSUE TITLE
нифига не понятно

### ISSUE THREAD

**Issue by 7dir** [amocrm/amocrm-oauth-client#3]
Всем привет!

Как может такая система известная иметь такую боль в документации.

1) документация всё время меняется и старые объяснения теряют силу, типа статей и видео
2) сделайте инфо-графику как делать интеграции, как ходят данные

**Comment by max-kut** [comment]
Да все нормально) Можешь глянуть в тестах моей библиотеки https://github.com/max-kut/AmoCRM 
Там как раз используется автоматическая аутентификация
